name: FastAPI CI/CD Pipeline

on:
  push:
    branches:
      - master  # jab master branch pe push hoga tab ye run hoga
  pull_request:
    branches:
      - master  # jab pull request banega tab ye run hoga

jobs:
  # Step 1: Setup Python environment
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # yahan apne project ke liye python version specify karo

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Run tests
      run: |
        source venv/bin/activate
        pytest  # test cases run karne ke liye pytest use karo

  # Step 2: Docker build and push (optional, agar Docker setup karna ho)
  docker-deploy:
    runs-on: ubuntu-latest
    needs: build  # pehle build job run hoga, fir docker-deploy run hoga

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image
      run: |
        docker build -t yourdockerhubusername/fastapi-app .
        docker push yourdockerhubusername/fastapi-app
